### 1. 创建房源
POST http://localhost:8080/api/house/resource/create
Content-Type: application/json

{}

### 2. 创建用户
POST http://localhost:8080/api/user/create
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "email": "test@example.com",
  "phone": "13800138000"
}


### 3. 用户登录
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

